Repository courselab/snaskii22, pull requests merged in 2022-11, with the labels that each got.

#2 doc : additional source annotations for newcomer contributors (fixes #1)
  TODO
  bootstrap.sh
  src/Makefile.am
  src/snaskii.c
Labels: good first issue

#4 Update source headers
  Makefile.am
  bootstrap.sh
  src/Makefile.am
  src/snaskii.c
  src/snaskii.sh
  src/utils.c
  src/utils.h
Labels: doc

#7 feat: add support for nix shell
  README.md
  flake.lock
  flake.nix
  nix/default.nix
  nix/shell.nix
Labels: feature

#14 fix(makefile): correct the install target
  nix/default.nix
  src/Makefile.am
Labels: bug, critical

#29 doc: fixing typo on snakii command
  README.md
Labels: tidy
