Repository courselab/snaskii22, pull requests merged in 2022-12, with the labels that each got.

#39 hot: rename doc to docs
  README.md
  docs/CONTRIBUTING.md
  docs/CONTRIBUTING.md.backup
  docs/CONTRIBUTING.md~
Labels: doc, tidy

#44 hot: CI for checking C Build
  .github/workflows/c-cpp.yml
Labels: question, tidy

#62 tidy: bring CI to develop branch
  .github/workflows/c-cpp.yml
Labels: tidy

#70 tidy: removed utils.c file
  src/utils.c
Labels: tidy

#38 make snake movement
  scenes/game/scene-0000001.txt
  src/Makefile.am
  src/snake.c
  src/snake.h
  src/snaskii.c
Labels: feature

#83 Correct grammar mistakes
  README.md
Labels: doc

#64 tidy: add a first version of a editor config
  .editorconfig
Labels: doc, help wanted, tidy

#138 newer version of spawning energy blocks
  src/graphics.c
  src/graphics.h
  src/snake.c
  src/snake.h
  src/snaskii.c
Labels: feature
